~/nrniv -c "degc=10" -c "bp=1.0" init.hoc
~/nrniv -c "degc=12" -c "bp=1.0" init.hoc
~/nrniv -c "degc=14" -c "bp=1.0" init.hoc
~/nrniv -c "degc=16" -c "bp=1.0" init.hoc
~/nrniv -c "degc=18" -c "bp=1.0" init.hoc
~/nrniv -c "degc=20" -c "bp=1.0" init.hoc
~/nrniv -c "degc=22" -c "bp=1.0" init.hoc
~/nrniv -c "degc=24" -c "bp=1.0" init.hoc
~/nrniv -c "degc=26" -c "bp=1.0" init.hoc
~/nrniv -c "degc=28" -c "bp=1.0" init.hoc
~/nrniv -c "degc=30" -c "bp=1.0" init.hoc
~/nrniv -c "degc=32" -c "bp=1.0" init.hoc
~/nrniv -c "degc=34" -c "bp=1.0" init.hoc
~/nrniv -c "degc=36" -c "bp=1.0" init.hoc
